package com.wom.dataobject;

import java.util.Date;

public class ProblemDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.id
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.feedBack
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.disposeBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String disposeby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.departmentby
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String departmentby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.studentName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String studentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.studentPhone
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String studentphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.teacherName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String teachername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.workType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String worktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.problemType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private Byte problemtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.problem
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.dispose
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String dispose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.sourceType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private Byte sourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.createBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.createTime
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.update_by
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wo_problem.update_at
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.id
     *
     * @return the value of wo_problem.id
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.id
     *
     * @param id the value for wo_problem.id
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.feedBack
     *
     * @return the value of wo_problem.feedBack
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.feedBack
     *
     * @param feedback the value for wo_problem.feedBack
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.disposeBy
     *
     * @return the value of wo_problem.disposeBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getDisposeby() {
        return disposeby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.disposeBy
     *
     * @param disposeby the value for wo_problem.disposeBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setDisposeby(String disposeby) {
        this.disposeby = disposeby == null ? null : disposeby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.departmentby
     *
     * @return the value of wo_problem.departmentby
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getDepartmentby() {
        return departmentby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.departmentby
     *
     * @param departmentby the value for wo_problem.departmentby
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setDepartmentby(String departmentby) {
        this.departmentby = departmentby == null ? null : departmentby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.studentName
     *
     * @return the value of wo_problem.studentName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.studentName
     *
     * @param studentname the value for wo_problem.studentName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.studentPhone
     *
     * @return the value of wo_problem.studentPhone
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getStudentphone() {
        return studentphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.studentPhone
     *
     * @param studentphone the value for wo_problem.studentPhone
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setStudentphone(String studentphone) {
        this.studentphone = studentphone == null ? null : studentphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.teacherName
     *
     * @return the value of wo_problem.teacherName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.teacherName
     *
     * @param teachername the value for wo_problem.teacherName
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.workType
     *
     * @return the value of wo_problem.workType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getWorktype() {
        return worktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.workType
     *
     * @param worktype the value for wo_problem.workType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setWorktype(String worktype) {
        this.worktype = worktype == null ? null : worktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.problemType
     *
     * @return the value of wo_problem.problemType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public Byte getProblemtype() {
        return problemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.problemType
     *
     * @param problemtype the value for wo_problem.problemType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setProblemtype(Byte problemtype) {
        this.problemtype = problemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.problem
     *
     * @return the value of wo_problem.problem
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.problem
     *
     * @param problem the value for wo_problem.problem
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.dispose
     *
     * @return the value of wo_problem.dispose
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getDispose() {
        return dispose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.dispose
     *
     * @param dispose the value for wo_problem.dispose
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setDispose(String dispose) {
        this.dispose = dispose == null ? null : dispose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.sourceType
     *
     * @return the value of wo_problem.sourceType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public Byte getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.sourceType
     *
     * @param sourcetype the value for wo_problem.sourceType
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setSourcetype(Byte sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.createBy
     *
     * @return the value of wo_problem.createBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.createBy
     *
     * @param createby the value for wo_problem.createBy
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.createTime
     *
     * @return the value of wo_problem.createTime
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.createTime
     *
     * @param createtime the value for wo_problem.createTime
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.update_by
     *
     * @return the value of wo_problem.update_by
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.update_by
     *
     * @param updateBy the value for wo_problem.update_by
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wo_problem.update_at
     *
     * @return the value of wo_problem.update_at
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wo_problem.update_at
     *
     * @param updateAt the value for wo_problem.update_at
     *
     * @mbggenerated Fri Dec 13 13:40:55 GMT+08:00 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}